const DISCOUNT_TYPE = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED'
};

const ORDER_STATUS = {
  INVOICE_ISSUED: 'INVOICE_ISSUED',
  IN_PRODUCTION: 'IN_PRODUCTION',
  READY_FOR_SHIPPING: 'READY_FOR_SHIPPING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  RETURNED_FOR_EXCHANGE: 'RETURNED_FOR_EXCHANGE',
  RECEIVED_FOR_EXCHANGE: 'RECEIVED_FOR_EXCHANGE',
  RETURNED: 'RETURNED'
};

module.exports.DISCOUNT_TYPE = DISCOUNT_TYPE;
module.exports.ORDER_STATUS = ORDER_STATUS;
